name: Release

on: [workflow_dispatch]

env:
 PROJECT_PATH: 'Rider.Setup\Rider.Setup.vdproj'
 DEVENV_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com'

jobs:
 deploy:
  runs-on: windows-latest
  steps:
    
  # Checkout code
  - name: Checkout code
    uses: actions/checkout@v3
    with:
     fetch-depth: 0
   
  # Install the .NET Core 
  - name: Install .NET Core
    uses: actions/setup-dotnet@v3
    with:
     dotnet-version: 7.0.x
    
  - run: dotnet restore ${{ env.PROJECT_PATH }} #Restores the dependencies and tools of a project.
  - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore
  - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build


    # Setup VS Dev Environment
  - name: Set VS.net environment
    run: cmd.exe /C CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
   
    # Build setup project
  - name: Build installer 
    run: cmd.exe /C CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com" ${{github.workspace}}${{ env.PROJECT_PATH }} /build "Release|Any CPU"

 