name: Release

on: [workflow_dispatch]

env:
 PROJECT_PATH: Rider.Setup/Rider.Setup.vdproj

jobs:
 deploy:
  runs-on: windows-latest
  steps:
    
  # Checkout code
  - name: Checkout code
    uses: actions/checkout@v3
    with:
     fetch-depth: 0
   
  # Install the .NET Core 
  - name: Install .NET Core
    uses: actions/setup-dotnet@v3
    with:
     dotnet-version: 7.0.x

    # Setup VS Dev Environment
  - name: Set VS.net environment
    run: cmd.exe /C CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
   
    # Build setup project
  - name: Build installer 
    run: devenv.com ${{github.workspace}}${{ env.PROJECT_PATH }} /build "Release|Any CPU"

 